### ISSUE TITLE
It (sh|c)ould not include a command bus impl

### ISSUE THREAD

**Issue by docteurklein** [RayRutjes/domain-foundation#7]
Some command bus impl exist already (like https://github.com/SimpleBus).
I guess it would be better to keep things separated since event sourcing has nothing to do with the command pattern.

**Comment by rayrutjes** [comment]
In the end, we want to provide the users with a full stack framework. My communication on event sourcing is a bit confusing, I have to blame the 140 chars available in twitter... It is left to the appreciation of everyone to work with the shipped command buses, or to create a little adapter for existing ones.
I think it is important to have some default, simple implementations out of the box, that illustrate a good integration in the whole picture.

That said, I keep in mind your remark, and I might wanna decouple things a bit, but I first wanna make sure, the implementations are a bit more stable.

First thing first, I am gonna re-write my tests in PhpUnit because I wanna use assertions, limit mocks, and limit factories, and this will benefit the community, phpunit being far more used.

Then I am going to add some features like: OptimisticLocking/ConflictResolving, which are really necessary for production.

Then we will figure out how we re-dispatch every single part of the lib. We even might left outside the command bus as suggested if that feels right at that time.

Does that sound good?
